// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTpxRUi2B9GFjLBWz44RJd5sHec5zmdF8',
    appId: '1:59143013970:web:12d301d13209b668d5c18b',
    messagingSenderId: '59143013970',
    projectId: 'tila-project',
    authDomain: 'tila-project.firebaseapp.com',
    storageBucket: 'tila-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEvbnGj5LZqlGndMosJHzHRJPrPccyah8',
    appId: '1:59143013970:android:7a3c720ed5a76370d5c18b',
    messagingSenderId: '59143013970',
    projectId: 'tila-project',
    storageBucket: 'tila-project.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTpxRUi2B9GFjLBWz44RJd5sHec5zmdF8',
    appId: '1:59143013970:web:1f7edec518eacfaed5c18b',
    messagingSenderId: '59143013970',
    projectId: 'tila-project',
    authDomain: 'tila-project.firebaseapp.com',
    storageBucket: 'tila-project.firebasestorage.app',
  );
}
